### ISSUE TITLE
Preferred emails and addresses

### ISSUE THREAD

**Issue by olisgail** [jweisman/alma-csv-user-load#10]
Would it be possible to add the ability to mark emails and addresses as “preferred”? Alma requires preferred addresses in order to send notices and letters. This would be especially useful because there is no other way to add that to users since the “Update/Notify Users” job does not include that feature.

Thanks for considering.

Gail Pawlowski
State University of New York (SUNY)

**Comment by jweisman** [comment]
Hi @olisgail . Thanks for your suggestion. Do you mean that we should mark the provided email / address as preferred? Or that we should offer the option to mark an email / address as preferred?

**Comment by olisgail** [comment]
Hi Josh,
Thanks for the reply. 
I suppose the ideal and most flexible solution would be the second option (the option to mark an email / address as preferred). But to be honest this app would probably only be used for loading one email address so either option would work.
Thanks again.
Gail
State University of New York (SUNY)

**Comment by jweisman** [comment]
Thanks- will try to work on this.

**Comment by jweisman** [comment]
Hi @olisgail - we have added the preferred attribute to the first email, phone, and address provided. Let us know how that works for you.

**Comment by olisgail** [comment]
Hi Josh,
Thanks so much for doing this. It worked and it makes the application much more useful.
Now if only it could update users it would be perfect!    :-)
Thanks again!

Gail
