### ISSUE TITLE
Add ability to update users

### ISSUE THREAD

**Issue by olisgail** [jweisman/alma-csv-user-load#11]
I just wanted to second the request to add the ability to update user records. This would be useful for libraries that don't have an IT department to create XML files for them. It would also be a great workaround to adding functionality to updating user records that the “Update/Notify Users” job does not provide.

Thanks for considering!

Gail Pawlowski
State University of New York (SUNY)

**Comment by jweisman** [comment]
Thanks for this suggestion. We have this request logged as issue #7. You can subscribe to notifications on that issue to get any updates.
