### ISSUE TITLE
Add Primary ID for failed deletes?

### ISSUE THREAD

**Issue by bkelm** [jweisman/alma-csv-user-load#13]
This works great for deletes, I know we get Primary ID's of processed results, would it be possible to get Primary ID's for failed ones? I know I could go back to Analytics and create another report the next day to gather too.

"Failed: Request failed: User cannot be deleted - A fine fee of 29.00 USD is attached to this user."

**Comment by jweisman** [comment]
Thanks for your request. We'll look into adding this.

**Comment by jweisman** [comment]
Hi @bkelm . We added the primary ID, first name, and last name to the error message when a record can't be added/updated. Hope this helps.

```
Failed: Given email type (school) is not supported for given user record type (STAFF). (csvload102, Weisman, Hank)
```

**Comment by bkelm** [comment]
Close, but I need something about the user when it can not be deleted.

**Comment by jweisman** [comment]
Hi @bkelm - can you elaborate? What additional information would you like to see other than the primary ID, first name, and last name?

**Comment by bkelm** [comment]
I think just the primary ID is fine, as the user information is still in Alma.

**Comment by jweisman** [comment]
Hi @bkelm - maybe we're not on the same page : ) The primary ID should appear now in the error when a record cannot be deleted. The log will show the error message, and then the primary ID, first name and last name in parentheses, like this:
```
Failed: Given email type (school) is not supported for given user record type (STAFF). (csvload102, Weisman, Hank)
```

Are you able to see that when you get a failed delete?

**Comment by bkelm** [comment]
I am not able to see it, on version 1.6.1. I get the following in the log:

Failed: Request failed: User cannot be deleted - User is linked to an invoice.
Failed: Request failed: User cannot be deleted - A fine fee of 5.25 USD is attached to this user.
Failed: Request failed: User cannot be deleted - A fine fee of 36.50 USD is attached to this user.
Failed: Request failed: User cannot be deleted - User is linked to a loan

**Comment by jweisman** [comment]
Great! Thanks for explaining patiently what I was missing : )
