### ISSUE TITLE
record type "contact"

### ISSUE THREAD

**Issue by bettinakann** [jweisman/alma-csv-user-load#15]
Hi Josh,
App works fine and more or less intuitively. Is it possible to add the record_type to the profile configuration? I miss the possibility to add users with the record type "contact".   Or did I overlook something?

thanks and br 
Bettina

**Comment by jweisman** [comment]
Thanks for your comment. We can try to add record_type to the configuration. We'll update you shortly.

**Comment by jweisman** [comment]
Hi @bettinakann . We added support for the record type. See the [docs](https://github.com/jweisman/alma-csv-user-load/wiki/Alma-CSV-User-Load-Manual#supported-fields) for details. Hope this helps.

**Comment by bettinakann** [comment]
@jweisman Thanks! Works fine and helps us. Now we don´t have to transform the csv-file that we get from one of our customers into xml but can almost directly load it into their IZ. :-)
