### ISSUE TITLE
alma-csv-user-load: missing fields

### ISSUE THREAD

**Issue by leahbokar** [jweisman/alma-csv-user-load#4]
The following fields are missing in the mapping form of alma-csv-user-load:

1. Notes
2. User Stat Categories 
3. Gender 
4. Campus
5. Preferred Language
6. Preferred first name
7. Preferred last name
8. Preferred middle name
9. Purge Date

Thanks,
Leah

Below are examples of Notes, Stat Categories and Gender:

**Comment by jweisman** [comment]
Thanks @leahbokar - working on this. Note that the preferred name fields are already supported.

**Comment by jweisman** [comment]
Hi Leah- released a new version with these fields and updated the [help file](https://github.com/jweisman/alma-csv-user-load/wiki/Alma-CSV-User-Load-Manual#supported-fields).
