### ISSUE TITLE
Users cannot be loaded as External

### ISSUE THREAD

**Issue by leahbokar** [jweisman/alma-csv-user-load#5]
I've configured a profile, user type "External".
CSV file load to Alma produced an error- below. Not sure where to get the unique tracking ID mentioned in a report:

Parsing CSV file
Failed: 
The web server encountered an unexpected condition that prevented it from fulfilling the request. If the error persists, please use the unique tracking ID when reporting it.
Failed: 
The web server encountered an unexpected condition that prevented it from fulfilling the request. If the error persists, please use the unique tracking ID when reporting it.
Failed: 
The web server encountered an unexpected condition that prevented it from fulfilling the request. If the error persists, please use the unique tracking ID when reporting it.
Failed: 
The web server encountered an unexpected condition that prevented it from fulfilling the request. If the error persists, please use the unique tracking ID when reporting it.
Finished

**Comment by jweisman** [comment]
Hi @leahbokar . I was able to create external accounts. Can you please provide a screen shot of the profile configuration and a sample file? Thanks.

**Comment by leahbokar** [comment]
Hi @jweisman,

It doesn't let me to attach files.
Will email you my sample file and a screen shot.


Thanks,
Leah

**Comment by jweisman** [comment]
Thanks for the files @leahbokar . A few notes:
1. According to the error message I received, we need to include the CODE of an SIS integration profile when creating External users. 
```
Failed: External Id must be given for external user.
```
I added the ability to define an external system in the profile and added a default value (SIS1 in my case)
<img width="386" alt="Screen Shot 2020-07-30 at 7 15 43 " src="https://user-images.githubusercontent.com/80420/88880148-ac5b0500-d234-11ea-8945-d502deb6b48b.png">

2. The next error message was a missing identifier value:
```
Failed: Mandatory field is missing: User identifier value
```
I think you meant to define barcode in the default column for identifier type:
<img width="386" alt="Screen Shot 2020-07-30 at 7 18 16 " src="https://user-images.githubusercontent.com/80420/88880357-373bff80-d235-11ea-9024-21e3ea029c7b.png">

Once I did that the file ran successfully. 
```
Parsing CSV file
Created: 3305578
Created: 3455340
Created: 3355176
Finished
```

I appreciate you helping us iron out any issues in real-work scenarios! Please make those 2 changes to your profile and let me know how it goes.

**Comment by leahbokar** [comment]
Hi Josh,

I've updated my profile with two additional fixed values:

SIS ==> External System
BARCODE ==> Identifier Type 

I've got the following error - below.

1. Empty field address line1 was processed as mandatory + the error does not have user primary ID

Parsing CSV file
Failed: 
The web server encountered an unexpected condition that prevented it from fulfilling the request. If the error persists, please use the unique tracking ID when reporting it.
Failed: Mandatory field is missing: address line1
Created: 3305578
Created: 3355176
Created: 3455338
Created: 3455450
Created: 3305565
Failed: Mandatory field is missing: address line1
Failed: Identifier with type = BARCODE couldn't be added/updated. User with the same id (primary_id = 200056) exists.
Created: 3255749
Created: 3435529
Created: 3365575
Finished


Thanks,
Leah

**Comment by jweisman** [comment]
Thanks Leah. I'm glad you got it working, at least mostly.

1. The "unexpected error" message is unfortunate. I can make a change which will display the tracking number so that we can look into it further.
2. The mandatory fields are defined by the institution, I believe, as documented [here](https://knowledge.exlibrisgroup.com/Alma/Product_Documentation/010Alma_Online_Help_(English)/050Administration/040Configuring_User_Management/030Mandatory_Fields_Configuration). So I assume this error is correct.
3. If barcode is defined as cross-institution unique, then in face it cannot be added again- so I think this is correct too.
