### ISSUE TITLE
Some additions to "Alma CSV User Load Manual" Help page

### ISSUE THREAD

**Issue by leahbokar** [jweisman/alma-csv-user-load#6]
Hi Josh,

Some additions to the Help page:

1.	User Type
By default, the app loads users defined as internal. You can specify that a profile should load users defined as external by selecting the appropriate value in the drop down. For more on information on internal and external users in Alma, see this documentation.

**Leah**: if this tool is a supplement to SIS loader profile, then the app should load users defined as External (default).

2.	Field Mapping
Default- the value to be used if no value is specified 

**Leah**: include examples of the default values

(a)	User Contact Information

Address type (low case):
work
school
alternative
home

Email type (low case):
work
school
personal
alternative 

Phone type (low case):
office 
home
mobile

(b)	User Note Types (upper case)

OTHER (viewable in Discovery)
LIBRARY  
ADDRESS
BARCODE
CIRCULATION
ERP
GENERAL
REGISTRAR

Thanks,
Leah

**Comment by jweisman** [comment]
Thanks for this @leahbokar . I updated the [doc](https://github.com/jweisman/alma-csv-user-load/wiki/Alma-CSV-User-Load-Manual#supported-fields) with the phone, address, email, and note types. Regarding the first point, I'm not sure this tool is meant to supplement the SIS. Loading internal users is an equally valid use case (in fact, it was developed for an institution whose requirement was internal users). So I think we'll leave the default as-is, and of course it can be changed per profile.
