### ISSUE TITLE
Support updating users

### ISSUE THREAD

**Issue by leahbokar** [jweisman/alma-csv-user-load#7]
Hi Josh,

I have successfully loaded External users with Notes and Stat fields to Alma -- Profile and CSV input file are attached.
[patrons-file.zip](https://github.com/jweisman/alma-csv-user-load/files/5016229/patrons-file.zip)
 

When I tried to reload the same file, I've got this error:

Parsing CSV file
Failed: User with identifier aaa.bbb of type  already exists.
Failed: User with identifier ccc.nnn of type  already exists.
Finished

Thanks,
Leah

**Comment by jweisman** [comment]
Hi Leah,

For now the CSV loader supports only loading new users. Do you have a requirement to support updating existing users?

**Comment by leahbokar** [comment]
Hi Josh,

Alma SIS profile updates existing users and creates new users if the match is not found. A match is based on any user ID including Primary ID. 

Alma customers are loading users via SIS in "update" mode. 



Thanks,
Leah

**Comment by jweisman** [comment]
Hi @leahbokar & @olisgail. We have made some changes to support updating and deleting users. Please check out the [docs](https://github.com/jweisman/alma-csv-user-load/wiki/Alma-CSV-User-Load-Manual#profile-type) and let us know how it works for you. Thanks.

**Comment by mck1777** [comment]
Thanks for adding the update module. I have run into a glitch using it, however, and am looking for assistance.  Per the instructions [https://github.com/jweisman/alma-csv-user-load/wiki/Alma-CSV-User-Load-Manual] I was trying to add a note to existing users. But I get an error when I use GENERAL as a note type, it will allow me to add LIBRARY.
Below is my csv file that I used
Primary Identifier,User Group,NoteType,Note
2121EWS102,Faculty,GENERAL,mck moved to faculty for test
2121EWS105,Active Duty,GENERAL,PCS to HMX
 I get the following error
Parsing CSV file
Failed: The parameter note_type  is invalid. Received: GENERAL.
Failed: The parameter note_type  is invalid. Received: GENERAL.
Finished


Thanks
Maryclare

**Comment by jweisman** [comment]
Hi @mck1777 - thanks for your question. It looks like the correct type for general notes is 'POPUP'. We've updated the [docs](https://github.com/jweisman/alma-csv-user-load/wiki/Alma-CSV-User-Load-Manual#supported-fields) to reflect that. Let us know how that works for you.

**Comment by mck1777** [comment]
Thanks. I got that to work. When I try to save an OTHER note that is suppose to be viewable in discovery I am failing. The note gets added, but not viewable.

I have attached an image of an account. The one that is OTHER type was loaded via the cloud app.
![viewable](https://user-images.githubusercontent.com/72558867/95490092-b9e3e800-0965-11eb-9ac5-b7076de60e58.JPG)

We are trying to send notes to patrons via their accounts since we are still mostly remote.  

If you could point me to the correct procedure to add a viewable note as a job or via this app I would appreciate it.

Thanks 
Maryclare

**Comment by jweisman** [comment]
Thanks for your comment. We can add the "visible to patron" indicator to the app. Can you [open a new issue](https://github.com/jweisman/alma-csv-user-load/issues/new/choose) to request this? Thanks!

**Comment by jweisman** [comment]
Added in Version 1.1.0
