### ISSUE TITLE
CSV>XML Help (some additions)

### ISSUE THREAD

**Issue by leahbokar** [jweisman/alma-csv-user-load#8]
Hi Josh,

Please add the following to SV>XML Help page:

1. Identifier Type
- Out of the box user identifiers
BARCODE
INST_ID

2. Password
Force password change (TRUE/FALSE)

- Passwords are not stored in Alma. I think these fields should be removed. Please double check.

3. External System Code
- Add a note that this code is mandatory for External users. 
- Can be any *default* value. Example: SIS

4. Basic example
- Add one more example (just a header) with the field codes only, The default values (address/email/phone types) can be defined in the Mapping Default field.

Header:
user_group,univ_id,first_name,last_name,expiration_date,address_line1,address_line2,city,state,postal_code,phone_number,email_address,additional_identifier,stat_category_code1,stat_category_code2,stat_category_code3,note

The sample mapping is attached:

[CSV-XML-Mapping-Example.zip](https://github.com/jweisman/alma-csv-user-load/files/5018288/CSV-XML-Mapping-Example.zip)

Thanks,
Leah

**Comment by jweisman** [comment]
Thanks for your suggestions @leahbokar. I added 1, 3, and 4. The API does support receiving a password and it's stored in the Ex Libris Identity Provider. 

I'll leave this issue open in case you have additional edits.
